name: CI/CD Task

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.MY_IP }}
          username: root
          key: ${{ secrets.MY_KEY }}
    
      - name: Deploy code
        run: |
          ssh root@${{ secrets.MY_IP }} << 'EOF'
          cd /raghad/project || exit
          git pull origin main
          npm install
          pm2 restart server.js || pm2 start server.js
          EOF
