name: CI/CD Task

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up server.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.1'


      
      - name: Deploy to server
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.MY_KEY }}

      - name: Deploy code
        run: |
          ssh -T -o StrictHostKeyChecking=no root@168.119.254.41<< 'EOF'
          cd raghad
          cd project || exit
          git pull origin main
          npm install
          npm start &
          EOF
