name: CI/CD Task

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.MY_KEY}}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{168.119.254.41}} >> ~/.ssh/known_hosts

    - name: Deploy code
      run: |
        ssh ${{root}}@${{168.119.254.41} << 'EOF'
        cd /raghad/project || exit
        git pull origin main
        npm install
        pm2 restart server.js || pm2 start server.js
        EOF
