name: CI/CD Task

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.MY_IP }}
          username: root
          key: ${{ secrets.MY_KEY }}
          source: './' # Files to transfer
          target: '/raghad/project' # Target directory on the server

      - name: Deploy code
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.MY_IP }} << 'EOF'
          cd /raghad/project || exit
          git pull origin main
          npm install
          pm2 restart server.js || pm2 start server.js
          EOF
